### ISSUE TITLE
Pajé trace importing fails for traces I succeed in importing with previous versions of the importer

### ISSUE THREAD

**Issue by dosimont** [soctrace-inria/framesoc.importers#22]

**Comment by dosimont** [comment]
Removing this part (l. 127) in PajeImporter enables the parser to work :

//					if (status.equals(Status.CANCEL_STATUS) || monitor.isCanceled()) {
//						throw new SoCTraceException();
//					}

**Comment by generoso** [comment]
Note: if the returned status is CANCEL_STATUS, it means that the pj_dump execution returned a value different than 0. So there is a problem with the dumping, not with the importer. 

Have you tried dumping the same paje trace file manually? (i.e., `pj_dump file.trace > file.pjdump`).

**Comment by generoso** [comment]
Dumping manually I get something like this:

`*** Error in `./fr.inria.soctrace.tools.importer.paje/exe/pj_dump': double free or corruption (fasttop): 0x00000000007b69f0 ***`

The problem seems to be in the pj_dump executable.
