### ISSUE TITLE
pj_dump importer : Problem with integers written as float numbers

### ISSUE THREAD

**Issue by dosimont** [soctrace-inria/framesoc.importers#32]
Each time the trace contains timestamps like 0.000000, 1.000000, it generates an error (see arnaud and jean-marie's mails).

A temporary solution found by Lucas was to remove all the .000000 occurrences using sed

**Comment by generoso** [comment]
@dosimont could you provide the trace? Neither @ycorre nor me could reproduce.

**Comment by dosimont** [comment]
Speak with Arnaud & Jean-Marie...
