### ISSUE TITLE
Bug in paraver importer

### ISSUE THREAD

**Issue by dosimont** [soctrace-inria/framesoc.importers#47]
In the reference trace (1024), the last thread has a wrong name (1024.1024.1 instead of 1.1024.1), see the screenshot that shows a comparison paraver.

![capture d ecran de 2015-12-03 17 07 51](https://cloud.githubusercontent.com/assets/1575332/11565937/8eed18b4-99e0-11e5-834c-41f833d53ac4.png)

**Comment by ycorre** [comment]
Fixed in commit https://github.com/soctrace-inria/framesoc.importers/commit/0c3ea1747eee91275c3a620a12e1faf165e247fa
